import tkinter as tk
from tkinter import ttk
from os import system

country = ""

root = tk.Tk()

width = root.winfo_screenwidth()
height = root.winfo_screenheight()

main_frame = ttk.Frame(root)
main_frame.pack(fill=tk.BOTH, expand=1)

my_canvas = tk.Canvas(main_frame)
my_canvas.pack(side=tk.LEFT, fill=tk.BOTH, expand=1)

# scrollbar
my_scrollbar = tk.Scrollbar(main_frame, orient=tk.VERTICAL, command=my_canvas.yview)
my_scrollbar.pack(side=tk.RIGHT, fill=tk.Y)

# configure the canvas
my_canvas.configure(yscrollcommand=my_scrollbar.set)
my_canvas.bind(
    "<Configure>", lambda e: my_canvas.configure(scrollregion=my_canvas.bbox("all"))
)

second_frame = tk.Frame(my_canvas, width=1000, height=100)


def sel():
    global country
    country = ""
    country = var.get()
    print(country)


root.geometry("%dx%d" % (width, height))

root.title("DebtSim")

var = tk.StringVar()


def next():
    system("python3 next.py " + country)
    quit(0)


# Text
message = ttk.Label(second_frame, text="Pick a country:")
message.pack(anchor=tk.W)

# Select
exit_button = ttk.Button(second_frame, text="Select", command=next)

exit_button.pack(anchor=tk.W)

# Buttons
# Generated by generator.py


my_canvas.create_window((0, 0), window=second_frame, anchor="nw")
root.mainloop()
