import tkinter as tk
from tkinter import ttk
from os import system
from time import sleep

country = ""

root = tk.Tk()

width = root.winfo_screenwidth()
height = root.winfo_screenheight()

main_frame = ttk.Frame(root)
main_frame.pack(fill=tk.BOTH, expand=1)

my_canvas = tk.Canvas(main_frame)
my_canvas.pack(side=tk.LEFT, fill=tk.BOTH, expand=1)

# scrollbar
my_scrollbar = tk.Scrollbar(main_frame, orient=tk.VERTICAL, command=my_canvas.yview)
my_scrollbar.pack(side=tk.RIGHT, fill=tk.Y)

# configure the canvas
my_canvas.configure(yscrollcommand=my_scrollbar.set)
my_canvas.bind(
    "<Configure>", lambda e: my_canvas.configure(scrollregion=my_canvas.bbox("all"))
)

second_frame = tk.Frame(my_canvas, width=1000, height=100)


def sel():
    global country
    country = ""
    country = var.get()
    print(country)


root.geometry("%dx%d" % (width, height))

root.title("DebtSim")

var = tk.StringVar()


def next():
    root.withdraw()

    system('python3 next.py "' + country + '"')

    root.destroy()

    quit(0)


# Text
message = ttk.Label(second_frame, text="Pick a country:")
message.pack(anchor=tk.W)

# Select
exit_button = ttk.Button(second_frame, text="Select", command=next)

exit_button.pack(anchor=tk.W)

# Buttons
# Generated by generator.py
R1 = ttk.Radiobutton(
    second_frame, text="Afghanistan", variable=var, value="Afghanistan", command=sel
)
R1.pack(anchor=tk.W)
R2 = ttk.Radiobutton(
    second_frame, text="Aland Islands", variable=var, value="Aland Islands", command=sel
)
R2.pack(anchor=tk.W)
R3 = ttk.Radiobutton(
    second_frame, text="Albania", variable=var, value="Albania", command=sel
)
R3.pack(anchor=tk.W)
R4 = ttk.Radiobutton(
    second_frame, text="Algeria", variable=var, value="Algeria", command=sel
)
R4.pack(anchor=tk.W)
R5 = ttk.Radiobutton(
    second_frame,
    text="American Samoa",
    variable=var,
    value="American Samoa",
    command=sel,
)
R5.pack(anchor=tk.W)
R6 = ttk.Radiobutton(
    second_frame, text="Andorra", variable=var, value="Andorra", command=sel
)
R6.pack(anchor=tk.W)
R7 = ttk.Radiobutton(
    second_frame, text="Angola", variable=var, value="Angola", command=sel
)
R7.pack(anchor=tk.W)
R8 = ttk.Radiobutton(
    second_frame, text="Anguilla", variable=var, value="Anguilla", command=sel
)
R8.pack(anchor=tk.W)
R9 = ttk.Radiobutton(
    second_frame, text="Antartica", variable=var, value="Antartica", command=sel
)
R9.pack(anchor=tk.W)
R10 = ttk.Radiobutton(
    second_frame,
    text="Antigua and Barbuda",
    variable=var,
    value="Antigua and Barbuda",
    command=sel,
)
R10.pack(anchor=tk.W)
R11 = ttk.Radiobutton(
    second_frame, text="Argentina", variable=var, value="Argentina", command=sel
)
R11.pack(anchor=tk.W)
R12 = ttk.Radiobutton(
    second_frame, text="Armenia", variable=var, value="Armenia", command=sel
)
R12.pack(anchor=tk.W)
R13 = ttk.Radiobutton(
    second_frame, text="Aruba", variable=var, value="Aruba", command=sel
)
R13.pack(anchor=tk.W)
R14 = ttk.Radiobutton(
    second_frame, text="Australia", variable=var, value="Australia", command=sel
)
R14.pack(anchor=tk.W)
R15 = ttk.Radiobutton(
    second_frame, text="Austria", variable=var, value="Austria", command=sel
)
R15.pack(anchor=tk.W)
R16 = ttk.Radiobutton(
    second_frame, text="Azerbaijan", variable=var, value="Azerbaijan", command=sel
)
R16.pack(anchor=tk.W)
R17 = ttk.Radiobutton(
    second_frame, text="Bahamas", variable=var, value="Bahamas", command=sel
)
R17.pack(anchor=tk.W)
R18 = ttk.Radiobutton(
    second_frame, text="Bahrain", variable=var, value="Bahrain", command=sel
)
R18.pack(anchor=tk.W)
R19 = ttk.Radiobutton(
    second_frame, text="Bangladesh", variable=var, value="Bangladesh", command=sel
)
R19.pack(anchor=tk.W)
R20 = ttk.Radiobutton(
    second_frame, text="Barbados", variable=var, value="Barbados", command=sel
)
R20.pack(anchor=tk.W)
R21 = ttk.Radiobutton(
    second_frame, text="Belarus", variable=var, value="Belarus", command=sel
)
R21.pack(anchor=tk.W)
R22 = ttk.Radiobutton(
    second_frame, text="Belgium", variable=var, value="Belgium", command=sel
)
R22.pack(anchor=tk.W)
R23 = ttk.Radiobutton(
    second_frame, text="Belize", variable=var, value="Belize", command=sel
)
R23.pack(anchor=tk.W)
R24 = ttk.Radiobutton(
    second_frame, text="Benin", variable=var, value="Benin", command=sel
)
R24.pack(anchor=tk.W)
R25 = ttk.Radiobutton(
    second_frame, text="Bermuda", variable=var, value="Bermuda", command=sel
)
R25.pack(anchor=tk.W)
R26 = ttk.Radiobutton(
    second_frame, text="Bhutan", variable=var, value="Bhutan", command=sel
)
R26.pack(anchor=tk.W)
R27 = ttk.Radiobutton(
    second_frame, text="Bolivia", variable=var, value="Bolivia", command=sel
)
R27.pack(anchor=tk.W)
R28 = ttk.Radiobutton(
    second_frame,
    text="Bonaire, Sint Eustatius and Saba",
    variable=var,
    value="Bonaire, Sint Eustatius and Saba",
    command=sel,
)
R28.pack(anchor=tk.W)
R29 = ttk.Radiobutton(
    second_frame,
    text="Bosnia and Herzegovina",
    variable=var,
    value="Bosnia and Herzegovina",
    command=sel,
)
R29.pack(anchor=tk.W)
R30 = ttk.Radiobutton(
    second_frame, text="Botswana", variable=var, value="Botswana", command=sel
)
R30.pack(anchor=tk.W)
R31 = ttk.Radiobutton(
    second_frame, text="Brazil", variable=var, value="Brazil", command=sel
)
R31.pack(anchor=tk.W)
R32 = ttk.Radiobutton(
    second_frame,
    text="British Virgin Islands",
    variable=var,
    value="British Virgin Islands",
    command=sel,
)
R32.pack(anchor=tk.W)
R33 = ttk.Radiobutton(
    second_frame,
    text="Brunei Darussalam",
    variable=var,
    value="Brunei Darussalam",
    command=sel,
)
R33.pack(anchor=tk.W)
R34 = ttk.Radiobutton(
    second_frame, text="Bulgaria", variable=var, value="Bulgaria", command=sel
)
R34.pack(anchor=tk.W)
R35 = ttk.Radiobutton(
    second_frame, text="Burkina Faso", variable=var, value="Burkina Faso", command=sel
)
R35.pack(anchor=tk.W)
R36 = ttk.Radiobutton(
    second_frame, text="Burundi", variable=var, value="Burundi", command=sel
)
R36.pack(anchor=tk.W)
R37 = ttk.Radiobutton(
    second_frame, text="Cambodia", variable=var, value="Cambodia", command=sel
)
R37.pack(anchor=tk.W)
R38 = ttk.Radiobutton(
    second_frame, text="Cameroon", variable=var, value="Cameroon", command=sel
)
R38.pack(anchor=tk.W)
R39 = ttk.Radiobutton(
    second_frame, text="Canada", variable=var, value="Canada", command=sel
)
R39.pack(anchor=tk.W)
R40 = ttk.Radiobutton(
    second_frame, text="Cape Verde", variable=var, value="Cape Verde", command=sel
)
R40.pack(anchor=tk.W)
R41 = ttk.Radiobutton(
    second_frame,
    text="Cayman Islands",
    variable=var,
    value="Cayman Islands",
    command=sel,
)
R41.pack(anchor=tk.W)
R42 = ttk.Radiobutton(
    second_frame,
    text="Central African Republic",
    variable=var,
    value="Central African Republic",
    command=sel,
)
R42.pack(anchor=tk.W)
R43 = ttk.Radiobutton(
    second_frame, text="Chad", variable=var, value="Chad", command=sel
)
R43.pack(anchor=tk.W)
R44 = ttk.Radiobutton(
    second_frame, text="Chile", variable=var, value="Chile", command=sel
)
R44.pack(anchor=tk.W)
R45 = ttk.Radiobutton(
    second_frame, text="China", variable=var, value="China", command=sel
)
R45.pack(anchor=tk.W)
R46 = ttk.Radiobutton(
    second_frame,
    text="Christmas Island",
    variable=var,
    value="Christmas Island",
    command=sel,
)
R46.pack(anchor=tk.W)
R47 = ttk.Radiobutton(
    second_frame,
    text="Cocos and Keeling Islands",
    variable=var,
    value="Cocos and Keeling Islands",
    command=sel,
)
R47.pack(anchor=tk.W)
R48 = ttk.Radiobutton(
    second_frame, text="Colombia", variable=var, value="Colombia", command=sel
)
R48.pack(anchor=tk.W)
R49 = ttk.Radiobutton(
    second_frame, text="Comoros", variable=var, value="Comoros", command=sel
)
R49.pack(anchor=tk.W)
R50 = ttk.Radiobutton(
    second_frame, text="Congo", variable=var, value="Congo", command=sel
)
R50.pack(anchor=tk.W)
R51 = ttk.Radiobutton(
    second_frame, text="Cook Islands", variable=var, value="Cook Islands", command=sel
)
R51.pack(anchor=tk.W)
R52 = ttk.Radiobutton(
    second_frame, text="Costa Rica", variable=var, value="Costa Rica", command=sel
)
R52.pack(anchor=tk.W)
R53 = ttk.Radiobutton(
    second_frame, text="Cote d'Ivoire", variable=var, value="Cote d'Ivoire", command=sel
)
R53.pack(anchor=tk.W)
R54 = ttk.Radiobutton(
    second_frame, text="Croatia", variable=var, value="Croatia", command=sel
)
R54.pack(anchor=tk.W)
R55 = ttk.Radiobutton(
    second_frame, text="Cuba", variable=var, value="Cuba", command=sel
)
R55.pack(anchor=tk.W)
R56 = ttk.Radiobutton(
    second_frame, text="Curacao", variable=var, value="Curacao", command=sel
)
R56.pack(anchor=tk.W)
R57 = ttk.Radiobutton(
    second_frame, text="Cyprus", variable=var, value="Cyprus", command=sel
)
R57.pack(anchor=tk.W)
R58 = ttk.Radiobutton(
    second_frame,
    text="Democratic People's Republic of Korea",
    variable=var,
    value="Democratic People's Republic of Korea",
    command=sel,
)
R58.pack(anchor=tk.W)
R59 = ttk.Radiobutton(
    second_frame,
    text="Democratic Republic of the Congo",
    variable=var,
    value="Democratic Republic of the Congo",
    command=sel,
)
R59.pack(anchor=tk.W)
R60 = ttk.Radiobutton(
    second_frame, text="Denmark", variable=var, value="Denmark", command=sel
)
R60.pack(anchor=tk.W)
R61 = ttk.Radiobutton(
    second_frame, text="Djibouti", variable=var, value="Djibouti", command=sel
)
R61.pack(anchor=tk.W)
R62 = ttk.Radiobutton(
    second_frame, text="Dominica", variable=var, value="Dominica", command=sel
)
R62.pack(anchor=tk.W)
R63 = ttk.Radiobutton(
    second_frame,
    text="Dominican Republic",
    variable=var,
    value="Dominican Republic",
    command=sel,
)
R63.pack(anchor=tk.W)
R64 = ttk.Radiobutton(
    second_frame, text="Ecuador", variable=var, value="Ecuador", command=sel
)
R64.pack(anchor=tk.W)
R65 = ttk.Radiobutton(
    second_frame, text="Egypt", variable=var, value="Egypt", command=sel
)
R65.pack(anchor=tk.W)
R66 = ttk.Radiobutton(
    second_frame, text="El Salvador", variable=var, value="El Salvador", command=sel
)
R66.pack(anchor=tk.W)
R67 = ttk.Radiobutton(
    second_frame,
    text="Equatorial Guinea",
    variable=var,
    value="Equatorial Guinea",
    command=sel,
)
R67.pack(anchor=tk.W)
R68 = ttk.Radiobutton(
    second_frame, text="Eritrea", variable=var, value="Eritrea", command=sel
)
R68.pack(anchor=tk.W)
R69 = ttk.Radiobutton(
    second_frame, text="Estonia", variable=var, value="Estonia", command=sel
)
R69.pack(anchor=tk.W)
R70 = ttk.Radiobutton(
    second_frame, text="Ethiopia", variable=var, value="Ethiopia", command=sel
)
R70.pack(anchor=tk.W)
R71 = ttk.Radiobutton(
    second_frame,
    text="Faeroe Islands",
    variable=var,
    value="Faeroe Islands",
    command=sel,
)
R71.pack(anchor=tk.W)
R72 = ttk.Radiobutton(
    second_frame,
    text="Falkland Islands",
    variable=var,
    value="Falkland Islands",
    command=sel,
)
R72.pack(anchor=tk.W)
R73 = ttk.Radiobutton(
    second_frame, text="Fiji", variable=var, value="Fiji", command=sel
)
R73.pack(anchor=tk.W)
R74 = ttk.Radiobutton(
    second_frame, text="Finland", variable=var, value="Finland", command=sel
)
R74.pack(anchor=tk.W)
R75 = ttk.Radiobutton(
    second_frame, text="France", variable=var, value="France", command=sel
)
R75.pack(anchor=tk.W)
R76 = ttk.Radiobutton(
    second_frame, text="French Guiana", variable=var, value="French Guiana", command=sel
)
R76.pack(anchor=tk.W)
R77 = ttk.Radiobutton(
    second_frame,
    text="French Polynesia",
    variable=var,
    value="French Polynesia",
    command=sel,
)
R77.pack(anchor=tk.W)
R78 = ttk.Radiobutton(
    second_frame, text="Gabon", variable=var, value="Gabon", command=sel
)
R78.pack(anchor=tk.W)
R79 = ttk.Radiobutton(
    second_frame, text="Gambia", variable=var, value="Gambia", command=sel
)
R79.pack(anchor=tk.W)
R80 = ttk.Radiobutton(
    second_frame, text="Georgia", variable=var, value="Georgia", command=sel
)
R80.pack(anchor=tk.W)
R81 = ttk.Radiobutton(
    second_frame, text="Germany", variable=var, value="Germany", command=sel
)
R81.pack(anchor=tk.W)
R82 = ttk.Radiobutton(
    second_frame, text="Ghana", variable=var, value="Ghana", command=sel
)
R82.pack(anchor=tk.W)
R83 = ttk.Radiobutton(
    second_frame, text="Gibraltar", variable=var, value="Gibraltar", command=sel
)
R83.pack(anchor=tk.W)
R84 = ttk.Radiobutton(
    second_frame, text="Greece", variable=var, value="Greece", command=sel
)
R84.pack(anchor=tk.W)
R85 = ttk.Radiobutton(
    second_frame, text="Greenland", variable=var, value="Greenland", command=sel
)
R85.pack(anchor=tk.W)
R86 = ttk.Radiobutton(
    second_frame, text="Grenada", variable=var, value="Grenada", command=sel
)
R86.pack(anchor=tk.W)
R87 = ttk.Radiobutton(
    second_frame, text="Guadeloupe", variable=var, value="Guadeloupe", command=sel
)
R87.pack(anchor=tk.W)
R88 = ttk.Radiobutton(
    second_frame, text="Guam", variable=var, value="Guam", command=sel
)
R88.pack(anchor=tk.W)
R89 = ttk.Radiobutton(
    second_frame, text="Guatemala", variable=var, value="Guatemala", command=sel
)
R89.pack(anchor=tk.W)
R90 = ttk.Radiobutton(
    second_frame, text="Guernsey", variable=var, value="Guernsey", command=sel
)
R90.pack(anchor=tk.W)
R91 = ttk.Radiobutton(
    second_frame, text="Guinea", variable=var, value="Guinea", command=sel
)
R91.pack(anchor=tk.W)
R92 = ttk.Radiobutton(
    second_frame, text="Guinea-Bissau", variable=var, value="Guinea-Bissau", command=sel
)
R92.pack(anchor=tk.W)
R93 = ttk.Radiobutton(
    second_frame, text="Guyana", variable=var, value="Guyana", command=sel
)
R93.pack(anchor=tk.W)
R94 = ttk.Radiobutton(
    second_frame, text="Haiti", variable=var, value="Haiti", command=sel
)
R94.pack(anchor=tk.W)
R95 = ttk.Radiobutton(
    second_frame, text="Holy See", variable=var, value="Holy See", command=sel
)
R95.pack(anchor=tk.W)
R96 = ttk.Radiobutton(
    second_frame, text="Honduras", variable=var, value="Honduras", command=sel
)
R96.pack(anchor=tk.W)
R97 = ttk.Radiobutton(
    second_frame,
    text="Hong Kong Special Administrative Region of China",
    variable=var,
    value="Hong Kong Special Administrative Region of China",
    command=sel,
)
R97.pack(anchor=tk.W)
R98 = ttk.Radiobutton(
    second_frame, text="Hungary", variable=var, value="Hungary", command=sel
)
R98.pack(anchor=tk.W)
R99 = ttk.Radiobutton(
    second_frame, text="Iceland", variable=var, value="Iceland", command=sel
)
R99.pack(anchor=tk.W)
R100 = ttk.Radiobutton(
    second_frame, text="India", variable=var, value="India", command=sel
)
R100.pack(anchor=tk.W)
R101 = ttk.Radiobutton(
    second_frame, text="Indonesia", variable=var, value="Indonesia", command=sel
)
R101.pack(anchor=tk.W)
R102 = ttk.Radiobutton(
    second_frame,
    text="Iran (Islamic Republic of)",
    variable=var,
    value="Iran (Islamic Republic of)",
    command=sel,
)
R102.pack(anchor=tk.W)
R103 = ttk.Radiobutton(
    second_frame, text="Iraq", variable=var, value="Iraq", command=sel
)
R103.pack(anchor=tk.W)
R104 = ttk.Radiobutton(
    second_frame, text="Ireland", variable=var, value="Ireland", command=sel
)
R104.pack(anchor=tk.W)
R105 = ttk.Radiobutton(
    second_frame, text="Isle of Man", variable=var, value="Isle of Man", command=sel
)
R105.pack(anchor=tk.W)
R106 = ttk.Radiobutton(
    second_frame, text="Israel", variable=var, value="Israel", command=sel
)
R106.pack(anchor=tk.W)
R107 = ttk.Radiobutton(
    second_frame, text="Italy", variable=var, value="Italy", command=sel
)
R107.pack(anchor=tk.W)
R108 = ttk.Radiobutton(
    second_frame, text="Jamaica", variable=var, value="Jamaica", command=sel
)
R108.pack(anchor=tk.W)
R109 = ttk.Radiobutton(
    second_frame, text="Japan", variable=var, value="Japan", command=sel
)
R109.pack(anchor=tk.W)
R110 = ttk.Radiobutton(
    second_frame, text="Jersey", variable=var, value="Jersey", command=sel
)
R110.pack(anchor=tk.W)
R111 = ttk.Radiobutton(
    second_frame, text="Jordan", variable=var, value="Jordan", command=sel
)
R111.pack(anchor=tk.W)
R112 = ttk.Radiobutton(
    second_frame, text="Kazakhstan", variable=var, value="Kazakhstan", command=sel
)
R112.pack(anchor=tk.W)
R113 = ttk.Radiobutton(
    second_frame, text="Kenya", variable=var, value="Kenya", command=sel
)
R113.pack(anchor=tk.W)
R114 = ttk.Radiobutton(
    second_frame, text="Kiribati", variable=var, value="Kiribati", command=sel
)
R114.pack(anchor=tk.W)
R115 = ttk.Radiobutton(
    second_frame, text="Kuwait", variable=var, value="Kuwait", command=sel
)
R115.pack(anchor=tk.W)
R116 = ttk.Radiobutton(
    second_frame, text="Kyrgyzstan", variable=var, value="Kyrgyzstan", command=sel
)
R116.pack(anchor=tk.W)
R117 = ttk.Radiobutton(
    second_frame,
    text="Lao People's Democratic Republic",
    variable=var,
    value="Lao People's Democratic Republic",
    command=sel,
)
R117.pack(anchor=tk.W)
R118 = ttk.Radiobutton(
    second_frame, text="Latvia", variable=var, value="Latvia", command=sel
)
R118.pack(anchor=tk.W)
R119 = ttk.Radiobutton(
    second_frame, text="Lebanon", variable=var, value="Lebanon", command=sel
)
R119.pack(anchor=tk.W)
R120 = ttk.Radiobutton(
    second_frame, text="Lesotho", variable=var, value="Lesotho", command=sel
)
R120.pack(anchor=tk.W)
R121 = ttk.Radiobutton(
    second_frame, text="Liberia", variable=var, value="Liberia", command=sel
)
R121.pack(anchor=tk.W)
R122 = ttk.Radiobutton(
    second_frame, text="Libya", variable=var, value="Libya", command=sel
)
R122.pack(anchor=tk.W)
R123 = ttk.Radiobutton(
    second_frame, text="Liechtenstein", variable=var, value="Liechtenstein", command=sel
)
R123.pack(anchor=tk.W)
R124 = ttk.Radiobutton(
    second_frame, text="Lithuania", variable=var, value="Lithuania", command=sel
)
R124.pack(anchor=tk.W)
R125 = ttk.Radiobutton(
    second_frame, text="Luxembourg", variable=var, value="Luxembourg", command=sel
)
R125.pack(anchor=tk.W)
R126 = ttk.Radiobutton(
    second_frame,
    text="Macao Special Administrative Region of China",
    variable=var,
    value="Macao Special Administrative Region of China",
    command=sel,
)
R126.pack(anchor=tk.W)
R127 = ttk.Radiobutton(
    second_frame, text="Madagascar", variable=var, value="Madagascar", command=sel
)
R127.pack(anchor=tk.W)
R128 = ttk.Radiobutton(
    second_frame, text="Malawi", variable=var, value="Malawi", command=sel
)
R128.pack(anchor=tk.W)
R129 = ttk.Radiobutton(
    second_frame, text="Malaysia", variable=var, value="Malaysia", command=sel
)
R129.pack(anchor=tk.W)
R130 = ttk.Radiobutton(
    second_frame, text="Maldives", variable=var, value="Maldives", command=sel
)
R130.pack(anchor=tk.W)
R131 = ttk.Radiobutton(
    second_frame, text="Mali", variable=var, value="Mali", command=sel
)
R131.pack(anchor=tk.W)
R132 = ttk.Radiobutton(
    second_frame, text="Malta", variable=var, value="Malta", command=sel
)
R132.pack(anchor=tk.W)
R133 = ttk.Radiobutton(
    second_frame,
    text="Marshall Islands",
    variable=var,
    value="Marshall Islands",
    command=sel,
)
R133.pack(anchor=tk.W)
R134 = ttk.Radiobutton(
    second_frame, text="Martinique", variable=var, value="Martinique", command=sel
)
R134.pack(anchor=tk.W)
R135 = ttk.Radiobutton(
    second_frame, text="Mauritania", variable=var, value="Mauritania", command=sel
)
R135.pack(anchor=tk.W)
R136 = ttk.Radiobutton(
    second_frame, text="Mauritius", variable=var, value="Mauritius", command=sel
)
R136.pack(anchor=tk.W)
R137 = ttk.Radiobutton(
    second_frame, text="Mayotte", variable=var, value="Mayotte", command=sel
)
R137.pack(anchor=tk.W)
R138 = ttk.Radiobutton(
    second_frame, text="Mexico", variable=var, value="Mexico", command=sel
)
R138.pack(anchor=tk.W)
R139 = ttk.Radiobutton(
    second_frame,
    text="Micronesia (Federated States of)",
    variable=var,
    value="Micronesia (Federated States of)",
    command=sel,
)
R139.pack(anchor=tk.W)
R140 = ttk.Radiobutton(
    second_frame, text="Monaco", variable=var, value="Monaco", command=sel
)
R140.pack(anchor=tk.W)
R141 = ttk.Radiobutton(
    second_frame, text="Mongolia", variable=var, value="Mongolia", command=sel
)
R141.pack(anchor=tk.W)
R142 = ttk.Radiobutton(
    second_frame, text="Montenegro", variable=var, value="Montenegro", command=sel
)
R142.pack(anchor=tk.W)
R143 = ttk.Radiobutton(
    second_frame, text="Montserrat", variable=var, value="Montserrat", command=sel
)
R143.pack(anchor=tk.W)
R144 = ttk.Radiobutton(
    second_frame, text="Morocco", variable=var, value="Morocco", command=sel
)
R144.pack(anchor=tk.W)
R145 = ttk.Radiobutton(
    second_frame, text="Mozambique", variable=var, value="Mozambique", command=sel
)
R145.pack(anchor=tk.W)
R146 = ttk.Radiobutton(
    second_frame, text="Myanmar", variable=var, value="Myanmar", command=sel
)
R146.pack(anchor=tk.W)
R147 = ttk.Radiobutton(
    second_frame, text="Namibia", variable=var, value="Namibia", command=sel
)
R147.pack(anchor=tk.W)
R148 = ttk.Radiobutton(
    second_frame, text="Nauru", variable=var, value="Nauru", command=sel
)
R148.pack(anchor=tk.W)
R149 = ttk.Radiobutton(
    second_frame, text="Nepal", variable=var, value="Nepal", command=sel
)
R149.pack(anchor=tk.W)
R150 = ttk.Radiobutton(
    second_frame, text="Netherlands", variable=var, value="Netherlands", command=sel
)
R150.pack(anchor=tk.W)
R151 = ttk.Radiobutton(
    second_frame, text="New Caledonia", variable=var, value="New Caledonia", command=sel
)
R151.pack(anchor=tk.W)
R152 = ttk.Radiobutton(
    second_frame, text="New Zealand", variable=var, value="New Zealand", command=sel
)
R152.pack(anchor=tk.W)
R153 = ttk.Radiobutton(
    second_frame, text="Nicaragua", variable=var, value="Nicaragua", command=sel
)
R153.pack(anchor=tk.W)
R154 = ttk.Radiobutton(
    second_frame, text="Niger", variable=var, value="Niger", command=sel
)
R154.pack(anchor=tk.W)
R155 = ttk.Radiobutton(
    second_frame, text="Nigeria", variable=var, value="Nigeria", command=sel
)
R155.pack(anchor=tk.W)
R156 = ttk.Radiobutton(
    second_frame, text="Niue", variable=var, value="Niue", command=sel
)
R156.pack(anchor=tk.W)
R157 = ttk.Radiobutton(
    second_frame,
    text="Norfolk Island",
    variable=var,
    value="Norfolk Island",
    command=sel,
)
R157.pack(anchor=tk.W)
R158 = ttk.Radiobutton(
    second_frame,
    text="Northern Mariana Islands",
    variable=var,
    value="Northern Mariana Islands",
    command=sel,
)
R158.pack(anchor=tk.W)
R159 = ttk.Radiobutton(
    second_frame, text="Norway", variable=var, value="Norway", command=sel
)
R159.pack(anchor=tk.W)
R160 = ttk.Radiobutton(
    second_frame, text="Oman", variable=var, value="Oman", command=sel
)
R160.pack(anchor=tk.W)
R161 = ttk.Radiobutton(
    second_frame, text="Pakistan", variable=var, value="Pakistan", command=sel
)
R161.pack(anchor=tk.W)
R162 = ttk.Radiobutton(
    second_frame, text="Palau", variable=var, value="Palau", command=sel
)
R162.pack(anchor=tk.W)
R163 = ttk.Radiobutton(
    second_frame, text="Panama", variable=var, value="Panama", command=sel
)
R163.pack(anchor=tk.W)
R164 = ttk.Radiobutton(
    second_frame,
    text="Papua New Guinea",
    variable=var,
    value="Papua New Guinea",
    command=sel,
)
R164.pack(anchor=tk.W)
R165 = ttk.Radiobutton(
    second_frame, text="Paraguay", variable=var, value="Paraguay", command=sel
)
R165.pack(anchor=tk.W)
R166 = ttk.Radiobutton(
    second_frame, text="Peru", variable=var, value="Peru", command=sel
)
R166.pack(anchor=tk.W)
R167 = ttk.Radiobutton(
    second_frame, text="Philippines", variable=var, value="Philippines", command=sel
)
R167.pack(anchor=tk.W)
R168 = ttk.Radiobutton(
    second_frame, text="Pitcairn", variable=var, value="Pitcairn", command=sel
)
R168.pack(anchor=tk.W)
R169 = ttk.Radiobutton(
    second_frame, text="Poland", variable=var, value="Poland", command=sel
)
R169.pack(anchor=tk.W)
R170 = ttk.Radiobutton(
    second_frame, text="Portugal", variable=var, value="Portugal", command=sel
)
R170.pack(anchor=tk.W)
R171 = ttk.Radiobutton(
    second_frame, text="Puerto Rico", variable=var, value="Puerto Rico", command=sel
)
R171.pack(anchor=tk.W)
R172 = ttk.Radiobutton(
    second_frame, text="Qatar", variable=var, value="Qatar", command=sel
)
R172.pack(anchor=tk.W)
R173 = ttk.Radiobutton(
    second_frame,
    text="Republic of Korea",
    variable=var,
    value="Republic of Korea",
    command=sel,
)
R173.pack(anchor=tk.W)
R174 = ttk.Radiobutton(
    second_frame,
    text="Republic of Moldova",
    variable=var,
    value="Republic of Moldova",
    command=sel,
)
R174.pack(anchor=tk.W)
R175 = ttk.Radiobutton(
    second_frame, text="Reunion", variable=var, value="Reunion", command=sel
)
R175.pack(anchor=tk.W)
R176 = ttk.Radiobutton(
    second_frame, text="Romania", variable=var, value="Romania", command=sel
)
R176.pack(anchor=tk.W)
R177 = ttk.Radiobutton(
    second_frame,
    text="Russian Federation",
    variable=var,
    value="Russian Federation",
    command=sel,
)
R177.pack(anchor=tk.W)
R178 = ttk.Radiobutton(
    second_frame, text="Rwanda", variable=var, value="Rwanda", command=sel
)
R178.pack(anchor=tk.W)
R179 = ttk.Radiobutton(
    second_frame,
    text="Saint Barthelemy",
    variable=var,
    value="Saint Barthelemy",
    command=sel,
)
R179.pack(anchor=tk.W)
R180 = ttk.Radiobutton(
    second_frame,
    text="Saint Helena, Ascension, and Tristan da Cunha",
    variable=var,
    value="Saint Helena, Ascension, and Tristan da Cunha",
    command=sel,
)
R180.pack(anchor=tk.W)
R181 = ttk.Radiobutton(
    second_frame,
    text="Saint Kitts and Nevis",
    variable=var,
    value="Saint Kitts and Nevis",
    command=sel,
)
R181.pack(anchor=tk.W)
R182 = ttk.Radiobutton(
    second_frame, text="Saint Lucia", variable=var, value="Saint Lucia", command=sel
)
R182.pack(anchor=tk.W)
R183 = ttk.Radiobutton(
    second_frame,
    text="Saint Martin (French part)",
    variable=var,
    value="Saint Martin (French part)",
    command=sel,
)
R183.pack(anchor=tk.W)
R184 = ttk.Radiobutton(
    second_frame,
    text="Saint Pierre and Miquelon",
    variable=var,
    value="Saint Pierre and Miquelon",
    command=sel,
)
R184.pack(anchor=tk.W)
R185 = ttk.Radiobutton(
    second_frame,
    text="Saint Vincent and the Grenadines",
    variable=var,
    value="Saint Vincent and the Grenadines",
    command=sel,
)
R185.pack(anchor=tk.W)
R186 = ttk.Radiobutton(
    second_frame, text="Samoa", variable=var, value="Samoa", command=sel
)
R186.pack(anchor=tk.W)
R187 = ttk.Radiobutton(
    second_frame, text="San Marino", variable=var, value="San Marino", command=sel
)
R187.pack(anchor=tk.W)
R188 = ttk.Radiobutton(
    second_frame,
    text="Sao Tome and Principe",
    variable=var,
    value="Sao Tome and Principe",
    command=sel,
)
R188.pack(anchor=tk.W)
R189 = ttk.Radiobutton(
    second_frame, text="Saudi Arabia", variable=var, value="Saudi Arabia", command=sel
)
R189.pack(anchor=tk.W)
R190 = ttk.Radiobutton(
    second_frame, text="Senegal", variable=var, value="Senegal", command=sel
)
R190.pack(anchor=tk.W)
R191 = ttk.Radiobutton(
    second_frame, text="Serbia", variable=var, value="Serbia", command=sel
)
R191.pack(anchor=tk.W)
R192 = ttk.Radiobutton(
    second_frame, text="Seychelles", variable=var, value="Seychelles", command=sel
)
R192.pack(anchor=tk.W)
R193 = ttk.Radiobutton(
    second_frame, text="Sierra Leone", variable=var, value="Sierra Leone", command=sel
)
R193.pack(anchor=tk.W)
R194 = ttk.Radiobutton(
    second_frame, text="Singapore", variable=var, value="Singapore", command=sel
)
R194.pack(anchor=tk.W)
R195 = ttk.Radiobutton(
    second_frame,
    text="Sint Maarten (Dutch part)",
    variable=var,
    value="Sint Maarten (Dutch part)",
    command=sel,
)
R195.pack(anchor=tk.W)
R196 = ttk.Radiobutton(
    second_frame, text="Slovakia", variable=var, value="Slovakia", command=sel
)
R196.pack(anchor=tk.W)
R197 = ttk.Radiobutton(
    second_frame, text="Slovenia", variable=var, value="Slovenia", command=sel
)
R197.pack(anchor=tk.W)
R198 = ttk.Radiobutton(
    second_frame,
    text="Solomon Islands",
    variable=var,
    value="Solomon Islands",
    command=sel,
)
R198.pack(anchor=tk.W)
R199 = ttk.Radiobutton(
    second_frame, text="Somalia", variable=var, value="Somalia", command=sel
)
R199.pack(anchor=tk.W)
R200 = ttk.Radiobutton(
    second_frame, text="South Africa", variable=var, value="South Africa", command=sel
)
R200.pack(anchor=tk.W)
R201 = ttk.Radiobutton(
    second_frame, text="South Sudan", variable=var, value="South Sudan", command=sel
)
R201.pack(anchor=tk.W)
R202 = ttk.Radiobutton(
    second_frame, text="Spain", variable=var, value="Spain", command=sel
)
R202.pack(anchor=tk.W)
R203 = ttk.Radiobutton(
    second_frame, text="Sri Lanka", variable=var, value="Sri Lanka", command=sel
)
R203.pack(anchor=tk.W)
R204 = ttk.Radiobutton(
    second_frame,
    text="State of Palestine",
    variable=var,
    value="State of Palestine",
    command=sel,
)
R204.pack(anchor=tk.W)
R205 = ttk.Radiobutton(
    second_frame, text="Sudan", variable=var, value="Sudan", command=sel
)
R205.pack(anchor=tk.W)
R206 = ttk.Radiobutton(
    second_frame, text="Suriname", variable=var, value="Suriname", command=sel
)
R206.pack(anchor=tk.W)
R207 = ttk.Radiobutton(
    second_frame, text="Sweden", variable=var, value="Sweden", command=sel
)
R207.pack(anchor=tk.W)
R208 = ttk.Radiobutton(
    second_frame, text="Switzerland", variable=var, value="Switzerland", command=sel
)
R208.pack(anchor=tk.W)
R209 = ttk.Radiobutton(
    second_frame,
    text="Syrian Arab Republic",
    variable=var,
    value="Syrian Arab Republic",
    command=sel,
)
R209.pack(anchor=tk.W)
R210 = ttk.Radiobutton(
    second_frame, text="Taiwan", variable=var, value="Taiwan", command=sel
)
R210.pack(anchor=tk.W)
R211 = ttk.Radiobutton(
    second_frame, text="Tajikistan", variable=var, value="Tajikistan", command=sel
)
R211.pack(anchor=tk.W)
R212 = ttk.Radiobutton(
    second_frame, text="Thailand", variable=var, value="Thailand", command=sel
)
R212.pack(anchor=tk.W)
R213 = ttk.Radiobutton(
    second_frame, text="Timor-Leste", variable=var, value="Timor-Leste", command=sel
)
R213.pack(anchor=tk.W)
R214 = ttk.Radiobutton(
    second_frame, text="Togo", variable=var, value="Togo", command=sel
)
R214.pack(anchor=tk.W)
R215 = ttk.Radiobutton(
    second_frame, text="Tokelau", variable=var, value="Tokelau", command=sel
)
R215.pack(anchor=tk.W)
R216 = ttk.Radiobutton(
    second_frame, text="Tonga", variable=var, value="Tonga", command=sel
)
R216.pack(anchor=tk.W)
R217 = ttk.Radiobutton(
    second_frame,
    text="Trinidad and Tobago",
    variable=var,
    value="Trinidad and Tobago",
    command=sel,
)
R217.pack(anchor=tk.W)
R218 = ttk.Radiobutton(
    second_frame, text="Tunisia", variable=var, value="Tunisia", command=sel
)
R218.pack(anchor=tk.W)
R219 = ttk.Radiobutton(
    second_frame, text="Turkey", variable=var, value="Turkey", command=sel
)
R219.pack(anchor=tk.W)
R220 = ttk.Radiobutton(
    second_frame, text="Turkmenistan", variable=var, value="Turkmenistan", command=sel
)
R220.pack(anchor=tk.W)
R221 = ttk.Radiobutton(
    second_frame,
    text="Turks and Caicos Islands",
    variable=var,
    value="Turks and Caicos Islands",
    command=sel,
)
R221.pack(anchor=tk.W)
R222 = ttk.Radiobutton(
    second_frame, text="Tuvalu", variable=var, value="Tuvalu", command=sel
)
R222.pack(anchor=tk.W)
R223 = ttk.Radiobutton(
    second_frame, text="Uganda", variable=var, value="Uganda", command=sel
)
R223.pack(anchor=tk.W)
R224 = ttk.Radiobutton(
    second_frame, text="Ukraine", variable=var, value="Ukraine", command=sel
)
R224.pack(anchor=tk.W)
R225 = ttk.Radiobutton(
    second_frame,
    text="United Arab Emirates",
    variable=var,
    value="United Arab Emirates",
    command=sel,
)
R225.pack(anchor=tk.W)
R226 = ttk.Radiobutton(
    second_frame,
    text="United Kingdom of Great Britain and Northern Ireland",
    variable=var,
    value="United Kingdom of Great Britain and Northern Ireland",
    command=sel,
)
R226.pack(anchor=tk.W)
R227 = ttk.Radiobutton(
    second_frame,
    text="United Republic of Tanzania",
    variable=var,
    value="United Republic of Tanzania",
    command=sel,
)
R227.pack(anchor=tk.W)
R228 = ttk.Radiobutton(
    second_frame,
    text="United States Virgin Islands",
    variable=var,
    value="United States Virgin Islands",
    command=sel,
)
R228.pack(anchor=tk.W)
R229 = ttk.Radiobutton(
    second_frame,
    text="United States of America",
    variable=var,
    value="United States of America",
    command=sel,
)
R229.pack(anchor=tk.W)
R230 = ttk.Radiobutton(
    second_frame, text="Uruguay", variable=var, value="Uruguay", command=sel
)
R230.pack(anchor=tk.W)
R231 = ttk.Radiobutton(
    second_frame, text="Uzbekistan", variable=var, value="Uzbekistan", command=sel
)
R231.pack(anchor=tk.W)
R232 = ttk.Radiobutton(
    second_frame, text="Vanuatu", variable=var, value="Vanuatu", command=sel
)
R232.pack(anchor=tk.W)
R233 = ttk.Radiobutton(
    second_frame, text="Venezuela", variable=var, value="Venezuela", command=sel
)
R233.pack(anchor=tk.W)
R234 = ttk.Radiobutton(
    second_frame, text="Vietnam", variable=var, value="Vietnam", command=sel
)
R234.pack(anchor=tk.W)
R235 = ttk.Radiobutton(
    second_frame,
    text="Wallis and Futuna Islands",
    variable=var,
    value="Wallis and Futuna Islands",
    command=sel,
)
R235.pack(anchor=tk.W)
R236 = ttk.Radiobutton(
    second_frame,
    text="Western Sahara",
    variable=var,
    value="Western Sahara",
    command=sel,
)
R236.pack(anchor=tk.W)
R237 = ttk.Radiobutton(
    second_frame, text="Yemen", variable=var, value="Yemen", command=sel
)
R237.pack(anchor=tk.W)
R238 = ttk.Radiobutton(
    second_frame, text="Zambia", variable=var, value="Zambia", command=sel
)
R238.pack(anchor=tk.W)
R239 = ttk.Radiobutton(
    second_frame, text="Zimbabwe", variable=var, value="Zimbabwe", command=sel
)
R239.pack(anchor=tk.W)


my_canvas.create_window((0, 0), window=second_frame, anchor="nw")
root.mainloop()

system('python3 next.py "' + country + '"')
quit(0)
