R1 = ttk.Radiobutton(root, text="Afghanistan", variable=var, value="Afghanistan", command=sel)
R1.pack(anchor=tk.W)
R2 = ttk.Radiobutton(root, text="Albania", variable=var, value="Albania", command=sel)
R2.pack(anchor=tk.W)
R3 = ttk.Radiobutton(root, text="Algeria", variable=var, value="Algeria", command=sel)
R3.pack(anchor=tk.W)
R4 = ttk.Radiobutton(root, text="American Samoa", variable=var, value="American Samoa", command=sel)
R4.pack(anchor=tk.W)
R5 = ttk.Radiobutton(root, text="Andorra", variable=var, value="Andorra", command=sel)
R5.pack(anchor=tk.W)
R6 = ttk.Radiobutton(root, text="Angola", variable=var, value="Angola", command=sel)
R6.pack(anchor=tk.W)
R7 = ttk.Radiobutton(root, text="Anguilla", variable=var, value="Anguilla", command=sel)
R7.pack(anchor=tk.W)
R8 = ttk.Radiobutton(root, text="Antarctica", variable=var, value="Antarctica", command=sel)
R8.pack(anchor=tk.W)
R9 = ttk.Radiobutton(root, text="Antigua and Barbuda", variable=var, value="Antigua and Barbuda", command=sel)
R9.pack(anchor=tk.W)
R10 = ttk.Radiobutton(root, text="Argentina", variable=var, value="Argentina", command=sel)
R10.pack(anchor=tk.W)
R11 = ttk.Radiobutton(root, text="Armenia", variable=var, value="Armenia", command=sel)
R11.pack(anchor=tk.W)
R12 = ttk.Radiobutton(root, text="Aruba", variable=var, value="Aruba", command=sel)
R12.pack(anchor=tk.W)
R13 = ttk.Radiobutton(root, text="Australia", variable=var, value="Australia", command=sel)
R13.pack(anchor=tk.W)
R14 = ttk.Radiobutton(root, text="Austria", variable=var, value="Austria", command=sel)
R14.pack(anchor=tk.W)
R15 = ttk.Radiobutton(root, text="Azerbaijan", variable=var, value="Azerbaijan", command=sel)
R15.pack(anchor=tk.W)
R16 = ttk.Radiobutton(root, text="Bahamas", variable=var, value="Bahamas", command=sel)
R16.pack(anchor=tk.W)
R17 = ttk.Radiobutton(root, text="Bahrain", variable=var, value="Bahrain", command=sel)
R17.pack(anchor=tk.W)
R18 = ttk.Radiobutton(root, text="Bangladesh", variable=var, value="Bangladesh", command=sel)
R18.pack(anchor=tk.W)
R19 = ttk.Radiobutton(root, text="Barbados", variable=var, value="Barbados", command=sel)
R19.pack(anchor=tk.W)
R20 = ttk.Radiobutton(root, text="Belarus", variable=var, value="Belarus", command=sel)
R20.pack(anchor=tk.W)
R21 = ttk.Radiobutton(root, text="Belgium", variable=var, value="Belgium", command=sel)
R21.pack(anchor=tk.W)
R22 = ttk.Radiobutton(root, text="Belize", variable=var, value="Belize", command=sel)
R22.pack(anchor=tk.W)
R23 = ttk.Radiobutton(root, text="Benin", variable=var, value="Benin", command=sel)
R23.pack(anchor=tk.W)
R24 = ttk.Radiobutton(root, text="Bermuda", variable=var, value="Bermuda", command=sel)
R24.pack(anchor=tk.W)
R25 = ttk.Radiobutton(root, text="Bhutan", variable=var, value="Bhutan", command=sel)
R25.pack(anchor=tk.W)
R26 = ttk.Radiobutton(root, text="Bolivia", variable=var, value="Bolivia", command=sel)
R26.pack(anchor=tk.W)
R27 = ttk.Radiobutton(root, text="Bosnia and Herzegovina", variable=var, value="Bosnia and Herzegovina", command=sel)
R27.pack(anchor=tk.W)
R28 = ttk.Radiobutton(root, text="Botswana", variable=var, value="Botswana", command=sel)
R28.pack(anchor=tk.W)
R29 = ttk.Radiobutton(root, text="Bouvet Island", variable=var, value="Bouvet Island", command=sel)
R29.pack(anchor=tk.W)
R30 = ttk.Radiobutton(root, text="Brazil", variable=var, value="Brazil", command=sel)
R30.pack(anchor=tk.W)
R31 = ttk.Radiobutton(root, text="British Indian Ocean Territory", variable=var, value="British Indian Ocean Territory", command=sel)
R31.pack(anchor=tk.W)
R32 = ttk.Radiobutton(root, text="British Virgin Islands", variable=var, value="British Virgin Islands", command=sel)
R32.pack(anchor=tk.W)
R33 = ttk.Radiobutton(root, text="Brunei", variable=var, value="Brunei", command=sel)
R33.pack(anchor=tk.W)
R34 = ttk.Radiobutton(root, text="Bulgaria", variable=var, value="Bulgaria", command=sel)
R34.pack(anchor=tk.W)
R35 = ttk.Radiobutton(root, text="Burkina Faso", variable=var, value="Burkina Faso", command=sel)
R35.pack(anchor=tk.W)
R36 = ttk.Radiobutton(root, text="Burundi", variable=var, value="Burundi", command=sel)
R36.pack(anchor=tk.W)
R37 = ttk.Radiobutton(root, text="Cambodia", variable=var, value="Cambodia", command=sel)
R37.pack(anchor=tk.W)
R38 = ttk.Radiobutton(root, text="Cameroon", variable=var, value="Cameroon", command=sel)
R38.pack(anchor=tk.W)
R39 = ttk.Radiobutton(root, text="Canada", variable=var, value="Canada", command=sel)
R39.pack(anchor=tk.W)
R40 = ttk.Radiobutton(root, text="Cape Verde", variable=var, value="Cape Verde", command=sel)
R40.pack(anchor=tk.W)
R41 = ttk.Radiobutton(root, text="Caribbean Netherlands", variable=var, value="Caribbean Netherlands", command=sel)
R41.pack(anchor=tk.W)
R42 = ttk.Radiobutton(root, text="Cayman Islands", variable=var, value="Cayman Islands", command=sel)
R42.pack(anchor=tk.W)
R43 = ttk.Radiobutton(root, text="Central African Republic", variable=var, value="Central African Republic", command=sel)
R43.pack(anchor=tk.W)
R44 = ttk.Radiobutton(root, text="Chad", variable=var, value="Chad", command=sel)
R44.pack(anchor=tk.W)
R45 = ttk.Radiobutton(root, text="Chile", variable=var, value="Chile", command=sel)
R45.pack(anchor=tk.W)
R46 = ttk.Radiobutton(root, text="China", variable=var, value="China", command=sel)
R46.pack(anchor=tk.W)
R47 = ttk.Radiobutton(root, text="Christmas Island", variable=var, value="Christmas Island", command=sel)
R47.pack(anchor=tk.W)
R48 = ttk.Radiobutton(root, text="Cocos (Keeling) Islands", variable=var, value="Cocos (Keeling) Islands", command=sel)
R48.pack(anchor=tk.W)
R49 = ttk.Radiobutton(root, text="Colombia", variable=var, value="Colombia", command=sel)
R49.pack(anchor=tk.W)
R50 = ttk.Radiobutton(root, text="Comoros", variable=var, value="Comoros", command=sel)
R50.pack(anchor=tk.W)
R51 = ttk.Radiobutton(root, text="Cook Islands", variable=var, value="Cook Islands", command=sel)
R51.pack(anchor=tk.W)
R52 = ttk.Radiobutton(root, text="Costa Rica", variable=var, value="Costa Rica", command=sel)
R52.pack(anchor=tk.W)
R53 = ttk.Radiobutton(root, text="Croatia", variable=var, value="Croatia", command=sel)
R53.pack(anchor=tk.W)
R54 = ttk.Radiobutton(root, text="Cuba", variable=var, value="Cuba", command=sel)
R54.pack(anchor=tk.W)
R55 = ttk.Radiobutton(root, text="Curaçao", variable=var, value="Curaçao", command=sel)
R55.pack(anchor=tk.W)
R56 = ttk.Radiobutton(root, text="Cyprus", variable=var, value="Cyprus", command=sel)
R56.pack(anchor=tk.W)
R57 = ttk.Radiobutton(root, text="Czechia", variable=var, value="Czechia", command=sel)
R57.pack(anchor=tk.W)
R58 = ttk.Radiobutton(root, text="Côte d'Ivoire (Ivory Coast)", variable=var, value="Côte d'Ivoire (Ivory Coast)", command=sel)
R58.pack(anchor=tk.W)
R59 = ttk.Radiobutton(root, text="Denmark", variable=var, value="Denmark", command=sel)
R59.pack(anchor=tk.W)
R60 = ttk.Radiobutton(root, text="Djibouti", variable=var, value="Djibouti", command=sel)
R60.pack(anchor=tk.W)
R61 = ttk.Radiobutton(root, text="Dominica", variable=var, value="Dominica", command=sel)
R61.pack(anchor=tk.W)
R62 = ttk.Radiobutton(root, text="Dominican Republic", variable=var, value="Dominican Republic", command=sel)
R62.pack(anchor=tk.W)
R63 = ttk.Radiobutton(root, text="DR Congo", variable=var, value="DR Congo", command=sel)
R63.pack(anchor=tk.W)
R64 = ttk.Radiobutton(root, text="Ecuador", variable=var, value="Ecuador", command=sel)
R64.pack(anchor=tk.W)
R65 = ttk.Radiobutton(root, text="Egypt", variable=var, value="Egypt", command=sel)
R65.pack(anchor=tk.W)
R66 = ttk.Radiobutton(root, text="El Salvador", variable=var, value="El Salvador", command=sel)
R66.pack(anchor=tk.W)
R67 = ttk.Radiobutton(root, text="Equatorial Guinea", variable=var, value="Equatorial Guinea", command=sel)
R67.pack(anchor=tk.W)
R68 = ttk.Radiobutton(root, text="Eritrea", variable=var, value="Eritrea", command=sel)
R68.pack(anchor=tk.W)
R69 = ttk.Radiobutton(root, text="Estonia", variable=var, value="Estonia", command=sel)
R69.pack(anchor=tk.W)
R70 = ttk.Radiobutton(root, text="Eswatini (Swaziland)", variable=var, value="Eswatini (Swaziland)", command=sel)
R70.pack(anchor=tk.W)
R71 = ttk.Radiobutton(root, text="Ethiopia", variable=var, value="Ethiopia", command=sel)
R71.pack(anchor=tk.W)
R72 = ttk.Radiobutton(root, text="European Union", variable=var, value="European Union", command=sel)
R72.pack(anchor=tk.W)
R73 = ttk.Radiobutton(root, text="Falkland Islands", variable=var, value="Falkland Islands", command=sel)
R73.pack(anchor=tk.W)
R74 = ttk.Radiobutton(root, text="Faroe Islands", variable=var, value="Faroe Islands", command=sel)
R74.pack(anchor=tk.W)
R75 = ttk.Radiobutton(root, text="Fiji", variable=var, value="Fiji", command=sel)
R75.pack(anchor=tk.W)
R76 = ttk.Radiobutton(root, text="Finland", variable=var, value="Finland", command=sel)
R76.pack(anchor=tk.W)
R77 = ttk.Radiobutton(root, text="France", variable=var, value="France", command=sel)
R77.pack(anchor=tk.W)
R78 = ttk.Radiobutton(root, text="French Guiana", variable=var, value="French Guiana", command=sel)
R78.pack(anchor=tk.W)
R79 = ttk.Radiobutton(root, text="French Polynesia", variable=var, value="French Polynesia", command=sel)
R79.pack(anchor=tk.W)
R80 = ttk.Radiobutton(root, text="French Southern and Antarctic Lands", variable=var, value="French Southern and Antarctic Lands", command=sel)
R80.pack(anchor=tk.W)
R81 = ttk.Radiobutton(root, text="Gabon", variable=var, value="Gabon", command=sel)
R81.pack(anchor=tk.W)
R82 = ttk.Radiobutton(root, text="Gambia", variable=var, value="Gambia", command=sel)
R82.pack(anchor=tk.W)
R83 = ttk.Radiobutton(root, text="Georgia", variable=var, value="Georgia", command=sel)
R83.pack(anchor=tk.W)
R84 = ttk.Radiobutton(root, text="Germany", variable=var, value="Germany", command=sel)
R84.pack(anchor=tk.W)
R85 = ttk.Radiobutton(root, text="Ghana", variable=var, value="Ghana", command=sel)
R85.pack(anchor=tk.W)
R86 = ttk.Radiobutton(root, text="Gibraltar", variable=var, value="Gibraltar", command=sel)
R86.pack(anchor=tk.W)
R87 = ttk.Radiobutton(root, text="Greece", variable=var, value="Greece", command=sel)
R87.pack(anchor=tk.W)
R88 = ttk.Radiobutton(root, text="Greenland", variable=var, value="Greenland", command=sel)
R88.pack(anchor=tk.W)
R89 = ttk.Radiobutton(root, text="Grenada", variable=var, value="Grenada", command=sel)
R89.pack(anchor=tk.W)
R90 = ttk.Radiobutton(root, text="Guadeloupe", variable=var, value="Guadeloupe", command=sel)
R90.pack(anchor=tk.W)
R91 = ttk.Radiobutton(root, text="Guam", variable=var, value="Guam", command=sel)
R91.pack(anchor=tk.W)
R92 = ttk.Radiobutton(root, text="Guatemala", variable=var, value="Guatemala", command=sel)
R92.pack(anchor=tk.W)
R93 = ttk.Radiobutton(root, text="Guernsey", variable=var, value="Guernsey", command=sel)
R93.pack(anchor=tk.W)
R94 = ttk.Radiobutton(root, text="Guinea", variable=var, value="Guinea", command=sel)
R94.pack(anchor=tk.W)
R95 = ttk.Radiobutton(root, text="Guinea-Bissau", variable=var, value="Guinea-Bissau", command=sel)
R95.pack(anchor=tk.W)
R96 = ttk.Radiobutton(root, text="Guyana", variable=var, value="Guyana", command=sel)
R96.pack(anchor=tk.W)
R97 = ttk.Radiobutton(root, text="Haiti", variable=var, value="Haiti", command=sel)
R97.pack(anchor=tk.W)
R98 = ttk.Radiobutton(root, text="Heard Island and McDonald Islands", variable=var, value="Heard Island and McDonald Islands", command=sel)
R98.pack(anchor=tk.W)
R99 = ttk.Radiobutton(root, text="Honduras", variable=var, value="Honduras", command=sel)
R99.pack(anchor=tk.W)
R100 = ttk.Radiobutton(root, text="Hong Kong", variable=var, value="Hong Kong", command=sel)
R100.pack(anchor=tk.W)
R101 = ttk.Radiobutton(root, text="Hungary", variable=var, value="Hungary", command=sel)
R101.pack(anchor=tk.W)
R102 = ttk.Radiobutton(root, text="Iceland", variable=var, value="Iceland", command=sel)
R102.pack(anchor=tk.W)
R103 = ttk.Radiobutton(root, text="India", variable=var, value="India", command=sel)
R103.pack(anchor=tk.W)
R104 = ttk.Radiobutton(root, text="Indonesia", variable=var, value="Indonesia", command=sel)
R104.pack(anchor=tk.W)
R105 = ttk.Radiobutton(root, text="Iran", variable=var, value="Iran", command=sel)
R105.pack(anchor=tk.W)
R106 = ttk.Radiobutton(root, text="Iraq", variable=var, value="Iraq", command=sel)
R106.pack(anchor=tk.W)
R107 = ttk.Radiobutton(root, text="Ireland", variable=var, value="Ireland", command=sel)
R107.pack(anchor=tk.W)
R108 = ttk.Radiobutton(root, text="Isle of Man", variable=var, value="Isle of Man", command=sel)
R108.pack(anchor=tk.W)
R109 = ttk.Radiobutton(root, text="Israel", variable=var, value="Israel", command=sel)
R109.pack(anchor=tk.W)
R110 = ttk.Radiobutton(root, text="Italy", variable=var, value="Italy", command=sel)
R110.pack(anchor=tk.W)
R111 = ttk.Radiobutton(root, text="Jamaica", variable=var, value="Jamaica", command=sel)
R111.pack(anchor=tk.W)
R112 = ttk.Radiobutton(root, text="Japan", variable=var, value="Japan", command=sel)
R112.pack(anchor=tk.W)
R113 = ttk.Radiobutton(root, text="Jersey", variable=var, value="Jersey", command=sel)
R113.pack(anchor=tk.W)
R114 = ttk.Radiobutton(root, text="Jordan", variable=var, value="Jordan", command=sel)
R114.pack(anchor=tk.W)
R115 = ttk.Radiobutton(root, text="Kazakhstan", variable=var, value="Kazakhstan", command=sel)
R115.pack(anchor=tk.W)
R116 = ttk.Radiobutton(root, text="Kenya", variable=var, value="Kenya", command=sel)
R116.pack(anchor=tk.W)
R117 = ttk.Radiobutton(root, text="Kiribati", variable=var, value="Kiribati", command=sel)
R117.pack(anchor=tk.W)
R118 = ttk.Radiobutton(root, text="Kosovo", variable=var, value="Kosovo", command=sel)
R118.pack(anchor=tk.W)
R119 = ttk.Radiobutton(root, text="Kuwait", variable=var, value="Kuwait", command=sel)
R119.pack(anchor=tk.W)
R120 = ttk.Radiobutton(root, text="Kyrgyzstan", variable=var, value="Kyrgyzstan", command=sel)
R120.pack(anchor=tk.W)
R121 = ttk.Radiobutton(root, text="Laos", variable=var, value="Laos", command=sel)
R121.pack(anchor=tk.W)
R122 = ttk.Radiobutton(root, text="Latvia", variable=var, value="Latvia", command=sel)
R122.pack(anchor=tk.W)
R123 = ttk.Radiobutton(root, text="Lebanon", variable=var, value="Lebanon", command=sel)
R123.pack(anchor=tk.W)
R124 = ttk.Radiobutton(root, text="Lesotho", variable=var, value="Lesotho", command=sel)
R124.pack(anchor=tk.W)
R125 = ttk.Radiobutton(root, text="Liberia", variable=var, value="Liberia", command=sel)
R125.pack(anchor=tk.W)
R126 = ttk.Radiobutton(root, text="Libya", variable=var, value="Libya", command=sel)
R126.pack(anchor=tk.W)
R127 = ttk.Radiobutton(root, text="Liechtenstein", variable=var, value="Liechtenstein", command=sel)
R127.pack(anchor=tk.W)
R128 = ttk.Radiobutton(root, text="Lithuania", variable=var, value="Lithuania", command=sel)
R128.pack(anchor=tk.W)
R129 = ttk.Radiobutton(root, text="Luxembourg", variable=var, value="Luxembourg", command=sel)
R129.pack(anchor=tk.W)
R130 = ttk.Radiobutton(root, text="Macau", variable=var, value="Macau", command=sel)
R130.pack(anchor=tk.W)
R131 = ttk.Radiobutton(root, text="Madagascar", variable=var, value="Madagascar", command=sel)
R131.pack(anchor=tk.W)
R132 = ttk.Radiobutton(root, text="Malawi", variable=var, value="Malawi", command=sel)
R132.pack(anchor=tk.W)
R133 = ttk.Radiobutton(root, text="Malaysia", variable=var, value="Malaysia", command=sel)
R133.pack(anchor=tk.W)
R134 = ttk.Radiobutton(root, text="Maldives", variable=var, value="Maldives", command=sel)
R134.pack(anchor=tk.W)
R135 = ttk.Radiobutton(root, text="Mali", variable=var, value="Mali", command=sel)
R135.pack(anchor=tk.W)
R136 = ttk.Radiobutton(root, text="Malta", variable=var, value="Malta", command=sel)
R136.pack(anchor=tk.W)
R137 = ttk.Radiobutton(root, text="Marshall Islands", variable=var, value="Marshall Islands", command=sel)
R137.pack(anchor=tk.W)
R138 = ttk.Radiobutton(root, text="Martinique", variable=var, value="Martinique", command=sel)
R138.pack(anchor=tk.W)
R139 = ttk.Radiobutton(root, text="Mauritania", variable=var, value="Mauritania", command=sel)
R139.pack(anchor=tk.W)
R140 = ttk.Radiobutton(root, text="Mauritius", variable=var, value="Mauritius", command=sel)
R140.pack(anchor=tk.W)
R141 = ttk.Radiobutton(root, text="Mayotte", variable=var, value="Mayotte", command=sel)
R141.pack(anchor=tk.W)
R142 = ttk.Radiobutton(root, text="Mexico", variable=var, value="Mexico", command=sel)
R142.pack(anchor=tk.W)
R143 = ttk.Radiobutton(root, text="Micronesia", variable=var, value="Micronesia", command=sel)
R143.pack(anchor=tk.W)
R144 = ttk.Radiobutton(root, text="Moldova", variable=var, value="Moldova", command=sel)
R144.pack(anchor=tk.W)
R145 = ttk.Radiobutton(root, text="Monaco", variable=var, value="Monaco", command=sel)
R145.pack(anchor=tk.W)
R146 = ttk.Radiobutton(root, text="Mongolia", variable=var, value="Mongolia", command=sel)
R146.pack(anchor=tk.W)
R147 = ttk.Radiobutton(root, text="Montenegro", variable=var, value="Montenegro", command=sel)
R147.pack(anchor=tk.W)
R148 = ttk.Radiobutton(root, text="Montserrat", variable=var, value="Montserrat", command=sel)
R148.pack(anchor=tk.W)
R149 = ttk.Radiobutton(root, text="Morocco", variable=var, value="Morocco", command=sel)
R149.pack(anchor=tk.W)
R150 = ttk.Radiobutton(root, text="Mozambique", variable=var, value="Mozambique", command=sel)
R150.pack(anchor=tk.W)
R151 = ttk.Radiobutton(root, text="Myanmar", variable=var, value="Myanmar", command=sel)
R151.pack(anchor=tk.W)
R152 = ttk.Radiobutton(root, text="Namibia", variable=var, value="Namibia", command=sel)
R152.pack(anchor=tk.W)
R153 = ttk.Radiobutton(root, text="Nauru", variable=var, value="Nauru", command=sel)
R153.pack(anchor=tk.W)
R154 = ttk.Radiobutton(root, text="Nepal", variable=var, value="Nepal", command=sel)
R154.pack(anchor=tk.W)
R155 = ttk.Radiobutton(root, text="Netherlands", variable=var, value="Netherlands", command=sel)
R155.pack(anchor=tk.W)
R156 = ttk.Radiobutton(root, text="New Caledonia", variable=var, value="New Caledonia", command=sel)
R156.pack(anchor=tk.W)
R157 = ttk.Radiobutton(root, text="New Zealand", variable=var, value="New Zealand", command=sel)
R157.pack(anchor=tk.W)
R158 = ttk.Radiobutton(root, text="Nicaragua", variable=var, value="Nicaragua", command=sel)
R158.pack(anchor=tk.W)
R159 = ttk.Radiobutton(root, text="Niger", variable=var, value="Niger", command=sel)
R159.pack(anchor=tk.W)
R160 = ttk.Radiobutton(root, text="Nigeria", variable=var, value="Nigeria", command=sel)
R160.pack(anchor=tk.W)
R161 = ttk.Radiobutton(root, text="Niue", variable=var, value="Niue", command=sel)
R161.pack(anchor=tk.W)
R162 = ttk.Radiobutton(root, text="Norfolk Island", variable=var, value="Norfolk Island", command=sel)
R162.pack(anchor=tk.W)
R163 = ttk.Radiobutton(root, text="North Korea", variable=var, value="North Korea", command=sel)
R163.pack(anchor=tk.W)
R164 = ttk.Radiobutton(root, text="North Macedonia", variable=var, value="North Macedonia", command=sel)
R164.pack(anchor=tk.W)
R165 = ttk.Radiobutton(root, text="Northern Mariana Islands", variable=var, value="Northern Mariana Islands", command=sel)
R165.pack(anchor=tk.W)
R166 = ttk.Radiobutton(root, text="Norway", variable=var, value="Norway", command=sel)
R166.pack(anchor=tk.W)
R167 = ttk.Radiobutton(root, text="Oman", variable=var, value="Oman", command=sel)
R167.pack(anchor=tk.W)
R168 = ttk.Radiobutton(root, text="Pakistan", variable=var, value="Pakistan", command=sel)
R168.pack(anchor=tk.W)
R169 = ttk.Radiobutton(root, text="Palau", variable=var, value="Palau", command=sel)
R169.pack(anchor=tk.W)
R170 = ttk.Radiobutton(root, text="Palestine", variable=var, value="Palestine", command=sel)
R170.pack(anchor=tk.W)
R171 = ttk.Radiobutton(root, text="Panama", variable=var, value="Panama", command=sel)
R171.pack(anchor=tk.W)
R172 = ttk.Radiobutton(root, text="Papua New Guinea", variable=var, value="Papua New Guinea", command=sel)
R172.pack(anchor=tk.W)
R173 = ttk.Radiobutton(root, text="Paraguay", variable=var, value="Paraguay", command=sel)
R173.pack(anchor=tk.W)
R174 = ttk.Radiobutton(root, text="Peru", variable=var, value="Peru", command=sel)
R174.pack(anchor=tk.W)
R175 = ttk.Radiobutton(root, text="Philippines", variable=var, value="Philippines", command=sel)
R175.pack(anchor=tk.W)
R176 = ttk.Radiobutton(root, text="Pitcairn Islands", variable=var, value="Pitcairn Islands", command=sel)
R176.pack(anchor=tk.W)
R177 = ttk.Radiobutton(root, text="Poland", variable=var, value="Poland", command=sel)
R177.pack(anchor=tk.W)
R178 = ttk.Radiobutton(root, text="Portugal", variable=var, value="Portugal", command=sel)
R178.pack(anchor=tk.W)
R179 = ttk.Radiobutton(root, text="Puerto Rico", variable=var, value="Puerto Rico", command=sel)
R179.pack(anchor=tk.W)
R180 = ttk.Radiobutton(root, text="Qatar", variable=var, value="Qatar", command=sel)
R180.pack(anchor=tk.W)
R181 = ttk.Radiobutton(root, text="Republic of the Congo", variable=var, value="Republic of the Congo", command=sel)
R181.pack(anchor=tk.W)
R182 = ttk.Radiobutton(root, text="Romania", variable=var, value="Romania", command=sel)
R182.pack(anchor=tk.W)
R183 = ttk.Radiobutton(root, text="Russia", variable=var, value="Russia", command=sel)
R183.pack(anchor=tk.W)
R184 = ttk.Radiobutton(root, text="Rwanda", variable=var, value="Rwanda", command=sel)
R184.pack(anchor=tk.W)
R185 = ttk.Radiobutton(root, text="Réunion", variable=var, value="Réunion", command=sel)
R185.pack(anchor=tk.W)
R186 = ttk.Radiobutton(root, text="Saint Barthélemy", variable=var, value="Saint Barthélemy", command=sel)
R186.pack(anchor=tk.W)
R187 = ttk.Radiobutton(root, text="Saint Helena, Ascension and Tristan da Cunha", variable=var, value="Saint Helena, Ascension and Tristan da Cunha", command=sel)
R187.pack(anchor=tk.W)
R188 = ttk.Radiobutton(root, text="Saint Kitts and Nevis", variable=var, value="Saint Kitts and Nevis", command=sel)
R188.pack(anchor=tk.W)
R189 = ttk.Radiobutton(root, text="Saint Lucia", variable=var, value="Saint Lucia", command=sel)
R189.pack(anchor=tk.W)
R190 = ttk.Radiobutton(root, text="Saint Martin", variable=var, value="Saint Martin", command=sel)
R190.pack(anchor=tk.W)
R191 = ttk.Radiobutton(root, text="Saint Pierre and Miquelon", variable=var, value="Saint Pierre and Miquelon", command=sel)
R191.pack(anchor=tk.W)
R192 = ttk.Radiobutton(root, text="Saint Vincent and the Grenadines", variable=var, value="Saint Vincent and the Grenadines", command=sel)
R192.pack(anchor=tk.W)
R193 = ttk.Radiobutton(root, text="Samoa", variable=var, value="Samoa", command=sel)
R193.pack(anchor=tk.W)
R194 = ttk.Radiobutton(root, text="San Marino", variable=var, value="San Marino", command=sel)
R194.pack(anchor=tk.W)
R195 = ttk.Radiobutton(root, text="Saudi Arabia", variable=var, value="Saudi Arabia", command=sel)
R195.pack(anchor=tk.W)
R196 = ttk.Radiobutton(root, text="Senegal", variable=var, value="Senegal", command=sel)
R196.pack(anchor=tk.W)
R197 = ttk.Radiobutton(root, text="Serbia", variable=var, value="Serbia", command=sel)
R197.pack(anchor=tk.W)
R198 = ttk.Radiobutton(root, text="Seychelles", variable=var, value="Seychelles", command=sel)
R198.pack(anchor=tk.W)
R199 = ttk.Radiobutton(root, text="Sierra Leone", variable=var, value="Sierra Leone", command=sel)
R199.pack(anchor=tk.W)
R200 = ttk.Radiobutton(root, text="Singapore", variable=var, value="Singapore", command=sel)
R200.pack(anchor=tk.W)
R201 = ttk.Radiobutton(root, text="Sint Maarten", variable=var, value="Sint Maarten", command=sel)
R201.pack(anchor=tk.W)
R202 = ttk.Radiobutton(root, text="Slovakia", variable=var, value="Slovakia", command=sel)
R202.pack(anchor=tk.W)
R203 = ttk.Radiobutton(root, text="Slovenia", variable=var, value="Slovenia", command=sel)
R203.pack(anchor=tk.W)
R204 = ttk.Radiobutton(root, text="Solomon Islands", variable=var, value="Solomon Islands", command=sel)
R204.pack(anchor=tk.W)
R205 = ttk.Radiobutton(root, text="Somalia", variable=var, value="Somalia", command=sel)
R205.pack(anchor=tk.W)
R206 = ttk.Radiobutton(root, text="South Africa", variable=var, value="South Africa", command=sel)
R206.pack(anchor=tk.W)
R207 = ttk.Radiobutton(root, text="South Georgia", variable=var, value="South Georgia", command=sel)
R207.pack(anchor=tk.W)
R208 = ttk.Radiobutton(root, text="South Korea", variable=var, value="South Korea", command=sel)
R208.pack(anchor=tk.W)
R209 = ttk.Radiobutton(root, text="South Sudan", variable=var, value="South Sudan", command=sel)
R209.pack(anchor=tk.W)
R210 = ttk.Radiobutton(root, text="Spain", variable=var, value="Spain", command=sel)
R210.pack(anchor=tk.W)
R211 = ttk.Radiobutton(root, text="Sri Lanka", variable=var, value="Sri Lanka", command=sel)
R211.pack(anchor=tk.W)
R212 = ttk.Radiobutton(root, text="Sudan", variable=var, value="Sudan", command=sel)
R212.pack(anchor=tk.W)
R213 = ttk.Radiobutton(root, text="Suriname", variable=var, value="Suriname", command=sel)
R213.pack(anchor=tk.W)
R214 = ttk.Radiobutton(root, text="Svalbard and Jan Mayen", variable=var, value="Svalbard and Jan Mayen", command=sel)
R214.pack(anchor=tk.W)
R215 = ttk.Radiobutton(root, text="Sweden", variable=var, value="Sweden", command=sel)
R215.pack(anchor=tk.W)
R216 = ttk.Radiobutton(root, text="Switzerland", variable=var, value="Switzerland", command=sel)
R216.pack(anchor=tk.W)
R217 = ttk.Radiobutton(root, text="Syria", variable=var, value="Syria", command=sel)
R217.pack(anchor=tk.W)
R218 = ttk.Radiobutton(root, text="São Tomé and Príncipe", variable=var, value="São Tomé and Príncipe", command=sel)
R218.pack(anchor=tk.W)
R219 = ttk.Radiobutton(root, text="Taiwan", variable=var, value="Taiwan", command=sel)
R219.pack(anchor=tk.W)
R220 = ttk.Radiobutton(root, text="Tajikistan", variable=var, value="Tajikistan", command=sel)
R220.pack(anchor=tk.W)
R221 = ttk.Radiobutton(root, text="Tanzania", variable=var, value="Tanzania", command=sel)
R221.pack(anchor=tk.W)
R222 = ttk.Radiobutton(root, text="Thailand", variable=var, value="Thailand", command=sel)
R222.pack(anchor=tk.W)
R223 = ttk.Radiobutton(root, text="Timor-Leste", variable=var, value="Timor-Leste", command=sel)
R223.pack(anchor=tk.W)
R224 = ttk.Radiobutton(root, text="Togo", variable=var, value="Togo", command=sel)
R224.pack(anchor=tk.W)
R225 = ttk.Radiobutton(root, text="Tokelau", variable=var, value="Tokelau", command=sel)
R225.pack(anchor=tk.W)
R226 = ttk.Radiobutton(root, text="Tonga", variable=var, value="Tonga", command=sel)
R226.pack(anchor=tk.W)
R227 = ttk.Radiobutton(root, text="Trinidad and Tobago", variable=var, value="Trinidad and Tobago", command=sel)
R227.pack(anchor=tk.W)
R228 = ttk.Radiobutton(root, text="Tunisia", variable=var, value="Tunisia", command=sel)
R228.pack(anchor=tk.W)
R229 = ttk.Radiobutton(root, text="Turkey", variable=var, value="Turkey", command=sel)
R229.pack(anchor=tk.W)
R230 = ttk.Radiobutton(root, text="Turkmenistan", variable=var, value="Turkmenistan", command=sel)
R230.pack(anchor=tk.W)
R231 = ttk.Radiobutton(root, text="Turks and Caicos Islands", variable=var, value="Turks and Caicos Islands", command=sel)
R231.pack(anchor=tk.W)
R232 = ttk.Radiobutton(root, text="Tuvalu", variable=var, value="Tuvalu", command=sel)
R232.pack(anchor=tk.W)
R233 = ttk.Radiobutton(root, text="Uganda", variable=var, value="Uganda", command=sel)
R233.pack(anchor=tk.W)
R234 = ttk.Radiobutton(root, text="Ukraine", variable=var, value="Ukraine", command=sel)
R234.pack(anchor=tk.W)
R235 = ttk.Radiobutton(root, text="United Arab Emirates", variable=var, value="United Arab Emirates", command=sel)
R235.pack(anchor=tk.W)
R236 = ttk.Radiobutton(root, text="United Kingdom", variable=var, value="United Kingdom", command=sel)
R236.pack(anchor=tk.W)
R237 = ttk.Radiobutton(root, text="United States", variable=var, value="United States", command=sel)
R237.pack(anchor=tk.W)
R238 = ttk.Radiobutton(root, text="United States Virgin Islands", variable=var, value="United States Virgin Islands", command=sel)
R238.pack(anchor=tk.W)
R239 = ttk.Radiobutton(root, text="Uruguay", variable=var, value="Uruguay", command=sel)
R239.pack(anchor=tk.W)
R240 = ttk.Radiobutton(root, text="Uzbekistan", variable=var, value="Uzbekistan", command=sel)
R240.pack(anchor=tk.W)
R241 = ttk.Radiobutton(root, text="Vanuatu", variable=var, value="Vanuatu", command=sel)
R241.pack(anchor=tk.W)
R242 = ttk.Radiobutton(root, text="Vatican City (Holy See)", variable=var, value="Vatican City (Holy See)", command=sel)
R242.pack(anchor=tk.W)
R243 = ttk.Radiobutton(root, text="Venezuela", variable=var, value="Venezuela", command=sel)
R243.pack(anchor=tk.W)
R244 = ttk.Radiobutton(root, text="Vietnam", variable=var, value="Vietnam", command=sel)
R244.pack(anchor=tk.W)
R245 = ttk.Radiobutton(root, text="Wallis and Futuna", variable=var, value="Wallis and Futuna", command=sel)
R245.pack(anchor=tk.W)
R246 = ttk.Radiobutton(root, text="Western Sahara", variable=var, value="Western Sahara", command=sel)
R246.pack(anchor=tk.W)
R247 = ttk.Radiobutton(root, text="Yemen", variable=var, value="Yemen", command=sel)
R247.pack(anchor=tk.W)
R248 = ttk.Radiobutton(root, text="Zambia", variable=var, value="Zambia", command=sel)
R248.pack(anchor=tk.W)
R249 = ttk.Radiobutton(root, text="Zimbabwe", variable=var, value="Zimbabwe", command=sel)
R249.pack(anchor=tk.W)
R250 = ttk.Radiobutton(root, text="Åland Islands", variable=var, value="Åland Islands", command=sel)
R250.pack(anchor=tk.W)
